[build]
  command = "cd homebudget-ui && npm ci && npm run build -- --configuration production"
  publish = "homebudget-ui/dist/homebudget-ui"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200