import { ApplicationConfig, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from './core/auth.interceptor';
import {
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  Code2,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  FileText,
  Github,
  GraduationCap,
  LayoutDashboard,
  Layers3,
  Linkedin,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Phone,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  TerminalSquare,
  Trophy,
  User,
  UserRound,
  WalletCards,
  LucideAngularModule
} from 'lucide-angular';

const icons = {
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  Code2,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  FileText,
  Github,
  GraduationCap,
  LayoutDashboard,
  Layers3,
  Linkedin,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Phone,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  TerminalSquare,
  Trophy,
  User,
  UserRound,
  WalletCards
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(LucideAngularModule.pick(icons))
  ]
};
